name: Build

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: 检查存储库
        uses: actions/checkout@v2

      - name: 设置Node.js版本
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: 删除 .github 文件夹
        run: rm -rf .github

      - name: 安装依赖
        run: npm i

      - name: 安装一个干净的项目
        run: npm ci

      - name: npx编译
        run: npx tsc

      - name: 移除ts结尾的文件
        run: find . -name "*.ts" -type f -delete

      - name: 提交更改至main
        run: |
          git config --global user.name "73desi"
          git config --global user.email "2633043826@qq.com"
          git add .
          git commit -m "${{ github.event.head_commit.message }}"
          git push